name: dust

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      new-version:
        description: New version of the package
        type: string
        required: true
  push:
    branches: [main]
    paths:
      - .github/workflows/dust.yml
      - images/dust/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dust

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, i686, aarch64]
        libc: [musl, gnu]
        include:
          - base_image: docker.io/library/debian:bookworm-slim
            libc: gnu
          - base_image: docker.io/library/alpine:latest
            libc: musl
          - platform: linux/amd64
            arch: x86_64
          - platform: linux/386
            arch: i686
          - platform: linux/arm64
            arch: aarch64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.arch == 'x86_64' && matrix.libc == 'gnu' }}
            type=raw,value=${{ matrix.arch }}-${{ matrix.libc }}
            type=raw,value=${{ inputs.new-version }}-${{ matrix.arch }}-${{ matrix.libc }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ env.IMAGE_NAME }}
          file: ./images/${{ env.IMAGE_NAME }}/Containerfile
          push: true
          no-cache: true
          platforms: ${{ matrix.platform }}
          build-args: |
            BASE_IMAGE=${{ matrix.base_image }}
            ARCH=${{ matrix.arch }}
            LIBC_DIST=${{ matrix.libc }}
          tags: |
            ${{ steps.meta.outputs.tags }}

