name: host-spawn

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
    paths:
      - .github/workflows/host-spawn.yml
      - images/host-spawn/**

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: host-spawn

jobs:
  get-version:
    name: Get next host-spawn version
    runs-on: ubuntu-latest
    outputs:
      gh_version: ${{ steps.host-spawn-version.outputs.gh_version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Get next version
        id: host-spawn-version
        run: |
          current_version="$(grep -E "PACKAGE_VERSION=.+" images/${{ env.IMAGE_NAME }}/Containerfile | sed 's/.*=//')"
          echo $current_version
          latest_version="$(curl -sL https://api.github.com/repos/1player/host-spawn/releases/latest | jq -r '.tag_name')"
          echo $latest_version
          if [ "$current_version" != "$latest_version" ]; then
            next_version="$latest_version"
          fi
          echo $next_version
          echo "gh_version=${next_version}" >> $GITHUB_OUTPUT

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: get-version
    if: ${{ needs.get-version.outputs.gh_version != '' }}
    strategy:
      matrix:
        arch: [x86_64, i686, i386, armv7, aarch64]
        include:
          - platform: linux/amd64
            arch: x86_64
          - platform: linux/386
            arch: i386
          - platform: linux/386
            arch: i686
          - platform: linux/arm/v7
            arch: armv7
          - platform: linux/arm64
            arch: aarch64
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ matrix.arch == 'x86_64' }}
            type=raw,value=${{ matrix.arch }}
            type=raw,value=${{ needs.get-version.outputs.gh_version }}-${{ matrix.arch }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./images/${{ env.IMAGE_NAME }}
          file: ./images/${{ env.IMAGE_NAME }}/Containerfile
          push: true
          no-cache: true
          platforms: ${{ matrix.platform }}
          build-args: |
            ARCH=${{ matrix.arch }}
          tags: |
            ${{ steps.meta.outputs.tags }}
